{
 "title": "Custom Strapi Dashboard",
 "description": "Cds, Books and Electronics",
 "time": { "from": "2023-11-28T14:11:35.542Z", "to": "2023-11-29T02:11:35.542Z" },
 "panels": [
  {
   "title": "Cds",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT name,price,quantity from cds",
     "rawQueryText": "SELECT name,price,quantity from cds",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Books",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT name,price,quantity from books",
     "rawQueryText": "SELECT name,price,quantity from books",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Electronics",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT name,price,quantity from electronics",
     "rawQueryText": "SELECT name,price,quantity from electronics",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}